language: node_js
sudo: false
os:
  - linux
  - osx
node_js:
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.1"
  - "1.3"
  - "1.5"
  - "1.7"
  - "2.0"
  - "2.1"
  - "2.3"
  - "2.5"
  - "3.0"
  - "3.1"
  - "3.3"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"
matrix:
  allow_failures:
    - os: osx
notifications:
  email:
    on_success: never
script: "npm run-script test-cov"
after_script: "cat ./coverage/lcov.info | coveralls"
before_install:
  # nvm is not yet supported on osx, manually install
  - "git clone https://github.com/creationix/nvm.git /tmp/.nvm"
  - "source /tmp/.nvm/nvm.sh"
  - "nvm install $NODE_VERSION"
  - "nvm use $NODE_VERSION"
  - "npm update -g npm"
  - "npm --version"
